import LeftPane from "@/components/LeftPane";
import SocialNetworks from "@/components/SocialNetworks";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppinsSans = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsSans.variable} antialiased flex justify-between`}
      >
        <LeftPane />
        {children}
        <SocialNetworks />
      </body>
    </html>
  );
}
